import type { Metadata } from "next";
import OrganizationGuard from "@/components/service/organizationGuard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <div>
        <OrganizationGuard>
          {children}
        </OrganizationGuard>
    </div>
  );
}
